import type { Metadata } from 'next';
import { Red_Hat_Text } from 'next/font/google';
import './globals.css';
import { CartProvider } from './components/Context' // Import the CartProvider

const inter = Red_Hat_Text({ subsets: ['latin'] ,weight:['400','500','600','700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className + " bg-Rose-50"}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
